#!/bin/bash
# ##############################################################################
# ################################ pacget #####################################
# ##############################################################################
#            Copyright (c) 2017 Md. Jahidul Hamid
# 
# -----------------------------------------------------------------------------
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
# 
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
# 
#     * The names of its contributors may not be used to endorse or promote 
#       products derived from this software without specific prior written
#       permission.
#       
# Disclaimer:
# 
#     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#     AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#     IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#     ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
#     LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#     CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#     SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#     INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#     CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#     ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#     POSSIBILITY OF SUCH DAMAGE.
# ##############################################################################

version=1.0.1
pkgname=pacget



txtrst='\\e[0m'    # Text Reset
bldcyn='\\e[1;36m' # Cyan
bldgrn='\\e[1;32m' # Green
bldblu='\\e[1;34m' # Blue
bldwht='\\e[1;37m' # White
bldpur='\\e[1;35m' # Purple
bldylw='\\e[1;33m' # Yellow

third_bracket_color=$bldcyn
good_version_color=$bldgrn
bracket_text=$bldblu
package_name_color=$bldwht
repo_name_color=$bldpur
end_color=$txtrst
num_color=$bldylw

help="
#################################### $pkgname ####################################
########################## An Archlinux package manager ########################
################################################################################

All options works the same way as pacaur except the following:

    -s, --search        : search in both arch repo and AUR and selective install
    -sx, --searchx      : Same as -s with extensive search.


All other options are forwarded to pacaur.

################################################################################
"

msg_out(){
	printf "*** $*\n" #> /dev/stdout
}

_star_s(){
    if [ "$1" = '' ]; then
        title='**********'
    else
        title=" ($1) "
    fi
    local s="************************$title*****************************"
    printf "\n\n\n*** $s\n"
}

_star_e(){
    local s='***************************************************************'
    printf "*** $s\n"
}

err_out(){
	printf "\nE: $*\n" >&2
}

wrn_out(){
	printf "\nW: $*\n" >&2
}

err_exit(){
	err_out "$*"
	exit 1
}

empty_var_exit(){
    # $1 -> msg
    # $2 -> var
    if [ "$2" = '' ]; then
        err_exit "$1"
    fi
}

chkroot(){
	if [ "$(id -u)" != "0" ]; then
	  err_out "root access required."
	  exit 1
	fi
}

chknorm(){
	if [ "$(id -u)" = "0" ]; then
	  wrn_out "Running as root not recommended. May produce some problems. Better run as a normal user."
	  return 1
	fi
}

chkcmd(){
    if command -v "$1" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}


declare -a args

search=false
search_term=
searchx=false
while [ $# -gt 0 ]
do
    i=$1
    j=$2
    if [[ "$i" =~ ^-(-)?(.*)s(.*)$ ]] || [[ "$i" =~ ^-(-)?search$ ]]; then
        empty_var_exit "Search term not specified" "$j"
        search_term=$2
        search=true
        if [[ "$i" =~ ^-(-)?(.*)x(.*)$ ]] || [[ "$i" =~ ^-(-)?searchx$ ]]; then
            args+=("$(echo "$i" |sed -n -r -e 's/(.*s.*)x(.*)/\1\2/p')" "$j")
            searchx=true
        else
            args+=("$i" "$j")
        fi
        shift
    elif [[ "$i" = -h ]] || [[ "$i" = --help ]]; then
        args+=("$i")
        printf "%s\n" "$help"
    elif [[ "$i" = -v ]] || [[ "$i" = --version ]]; then
        args+=("$i")
        msg_out "$pkgname    version: $version"
        msg_out "pacaur     version: $(pacaur -v)"
        msg_out "pacman     version: $(pacman --version)"
        exit 1
    else
        args+=("$i")
    fi
    shift
done

search_results=
if $search; then
    search_results=$(
    pacaur -s "$search_term"
    pacman -Ss "$search_term"
    )
    if $searchx; then
        sudo pkgfile -u
        tmpres=$(pkgfile "$search_term")
        search_results="$tmpres$search_results"
    fi
fi

if $search; then
    raw_indexed_search_results=$(echo "$search_results" | awk 'BEGIN {a=0} /^[a-zA-Z]+\// {a++; print "\n" a,$0; next;} {print $0;}')
    #echo "$raw_indexed_search_results"

    search_results=$(
        echo "$raw_indexed_search_results" |
        sed -r \
            -e "s#^([0-9]+[[:blank:]]+[^[:blank:]/]+/[^[:blank:]]+[*[:blank:]]*[^][]*)(\[[^][]+\])#\1$third_bracket_color\2$end_color #" \
            -e "s#^([0-9]+[[:blank:]]+[^[:blank:]/]+/[^[:blank:]]+[*[:blank:]]*[^()]*)(\([^()]+\))#\1$bracket_text\2$end_color #" \
            -e "s#^([0-9]+[[:blank:]]+[^[:blank:]/]+/[^[:blank:]]+[*[:blank:]]*)([^[:blank:]]+)#\1$good_version_color\2$end_color #" \
            -e "s#^([0-9]+[[:blank:]]+[^[:blank:]/]+/)([^[:blank:]]+)[*[:blank:]]*#\1$package_name_color\2$end_color #" \
            -e "s#^([0-9]+[[:blank:]]+)([^[:blank:]/]+)/#\1$repo_name_color\2$end_color/#" \
            -e "s#^([0-9]+)[[:blank:]]+#$num_color\1$end_color #" \
        )

    printf "$search_results"

    if [[ "$search_results" != '' ]]; then
        msg="\n\n>>> Enter the sequences of packages to be installed.\n    Comma separated values (e.g 1,2,3)\n    or range (e.g 1,3-5,6-7): "
        msg=$(printf "$msg\n" | sed -r -e "s#.+#$bldwht&$end_color#")
        printf "$msg"
        read inp
        declare -a arr
        packs=
        arr=($(echo "$inp" |tr ',' '\n'))

        for p in "${arr[@]}"; do
            if [[ "$p" =~ ^[0-9]+$ ]]; then
                #echo "$p"
                packs+=" $(echo "$raw_indexed_search_results" | sed -r -n -e "s#^$p[[:blank:]]+[^/]+/([^[:blank:]]+).*#\1#p")"
            elif [[ "$p" =~ ^([0-9]+)[[:blank:]]*-[[:blank:]]*([0-9]+) ]]; then
                if [ ${BASH_REMATCH[1]} -gt ${BASH_REMATCH[2]} ]; then
                    lc=${BASH_REMATCH[2]}
                    uc=${BASH_REMATCH[1]}
                else
                    lc=${BASH_REMATCH[1]}
                    uc=${BASH_REMATCH[2]}
                fi
                for i in $(seq $lc $uc); do
                    packs+=" $(echo "$raw_indexed_search_results" | sed -r -n -e "s#^$i[[:blank:]]+[^/]+/([^[:blank:]]+).*#\1#p")"
                done
            else
                err_exit "Invalid range or sequence: $p"
            fi
        done
        if [[ "$packs" != '' ]]; then
            pacaur -Sy $packs
        fi
    fi
else
    pacaur "${args[@]}"
fi
